books/urls.py
from django.urls import path
from .views import results_book_view, add_book_view, find_book_view, find_book_failed_view

app_name = 'books'

urlpatterns = [
	path('add/', add_book_view, name='add'),
	path('find/', find_book_view, name='find'),
	path('results/', results_book_view, name='results'),
	path('find_failed/', find_book_failed_view, name='find_failed'),

]

books_library/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from pages.views import home_view, contact_view
import debug_toolbar


urlpatterns = [
    path('books/', include('books.urls')),
    path('users/', include('pages.urls')),

    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('contact/', contact_view, name='contact'),

    path('__debug__', include(debug_toolbar.urls)),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import add_book_view, library_view, account_view, register_user_view, login_user_view, update_user_view, \
	info_book_view, update_book_view, update_image_view

app_name = 'users'

urlpatterns = [
	path('delete/', add_book_view, name='delete'),
	path('library/', library_view, name='library'),
	path('account/', account_view, name='account'),
	path('register/', register_user_view, name='register'),
	path('login/', login_user_view, name='login'),
	path('update/', update_user_view, name='update'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('update_image/', update_image_view, name='update_image'),


	path('info_book/', info_book_view, name='info_book'),
	path('update_book/', update_book_view, name='update_book'),
]

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books Library</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/css/style.css">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-grey">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.jpg' %}" width="90" height="80"></a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

            <li class="nav-item">
                <a class="nav-link" href="">About</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:find' %}">Find books</a>
            </li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated == False %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
            {% endif %}

        {% if user.is_authenticated == True %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle article-img" src="{{ request.user.userimage.image.url }}" style="max-height:20px; max-width:20px; width:20%; height:20%">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'users:library' %}">Library</a>
                      <a class="dropdown-item" href="{% url 'users:account' %}">Profile</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                </div>
            </li>

            <!--NAVBAR SEARCHING FORM-->
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input id="title" name="title" class="form-control mr-sm-2" type="text"
                   placeholder="Search..." aria-label="Search">
            <input class="btn btn-outline-secondary my-2 my-sm-0" type="Submit" value="Find book" />
        </form>
        {% endif %}

        </ul>

    </div>
</nav>

{% block content %}
SOME STAFF TO REPLACE
{% endblock %}


<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{% block javascript %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        {% if user.get_username == '' %}
        <h1 class="display-4">Hello, New awesome books reader!</h1>
        {% else %}
        <h1 class="display-4">Hello, {{ request.user }}!</h1>
        {% endif %}
        <h2>This is a Books Library home page. </h2>
        <p class="lead">Some Reading Challange rules: </p>
        <ul>
            <li>
                Choose a book (or books) you want to read in current mounth.
            </li>
            <li>
                App will calculate how many pages per day you should read.
            </li>
            <li>
                Invite your family and friends to this challenge.
            </li>
            <li>
                If you don't make it, choose something you need to do (for example donate some $ to charity,
                give food to homeless people or take your boyfriend/girlfriend for a treat. It's all up to you.)
            </li>
            <li>
                You can check other player's profiles and find some inspiration for following months.
            </li>



        </ul>
        <hr class="my-4">
            {% if user.get_username == '' %}
            <p>Register to start your challange!</p>
                <p class="lead">
                    <a class="btn btn-primary btn-lg" id="register_user" href="{% url 'users:register' %}" role="button">Register!</a>
            {% else %}
            <p>Start with finding a book!</p>
                <p class="lead">
                    <a class="btn btn-primary btn-lg" id="find_book" href="{% url 'books:find' %}" role="button">Find book!</a>
            {% endif %}
        </p>
    </div>
</div>

{% endblock %}