books/urls.py
from django.urls import path
from .views import results_book_view, add_book_view, find_book_view, find_book_failed_view

app_name = 'books'

urlpatterns = [
	path('add/', add_book_view, name='add'),
	path('find/', find_book_view, name='find'),
	path('results/', results_book_view, name='results'),
	path('find_failed/', find_book_failed_view, name='find_failed'),

]

books_library/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from pages.views import home_view, contact_view
import debug_toolbar


urlpatterns = [
    path('books/', include('books.urls')),
    path('users/', include('pages.urls')),

    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('contact/', contact_view, name='contact'),

    path('__debug__', include(debug_toolbar.urls)),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import add_book_view, library_view, account_view, register_user_view, login_user_view, update_user_view, \
	info_book_view, update_book_view, update_image_view

app_name = 'users'

urlpatterns = [
	path('delete/', add_book_view, name='delete'),
	path('library/', library_view, name='library'),
	path('account/', account_view, name='account'),
	path('register/', register_user_view, name='register'),
	path('login/', login_user_view, name='login'),
	path('update/', update_user_view, name='update'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('update_image/', update_image_view, name='update_image'),


	path('info_book/', info_book_view, name='info_book'),
	path('update_book/', update_book_view, name='update_book'),
]

templates/users/account.html
{% extends 'base.html' %}

{% block content %}

<!--<div class="row justify-content-center">-->
<!--    <div class="col-lg-8 col-md-10 col-sm-12">-->
<!--        <div class="card">-->
<!--            <div class="card-body">-->
<!--                <p class="lead">Username: {{ request.user.username }}</p>-->
<!--                <hr class="my-4">-->
<!--                <p class="lead">Email: {{ user.email }}</p>-->
<!--                <hr class="my-4">-->
<!--                <a class="btn btn-primary btn-lg" href="{% url 'users:update' %}" role="button">Update</a>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<div class="container">

   <h1 class="text-center logo my-4">
      {{ request.user.username }}'s Info
   </h1>


    <div class="card mb-2" style="margin-left:5%; margin-right:10%;">
        <div class="card-body p-3" >
            <div class="row">

                <div class="col-3" style="">

                    <img src="{{ request.user.userimage.image.url }}" alt="connect" style="max-height:220px; max-width:220px;">
                </div>

                <div class="col-7">
                        <p class="lead">Username: {{ request.user.username }}</p>
                    <hr class="my-4">
                        <p class="lead">Email: {{ user.email }}</p>
                    <hr class="my-4">
                    <a class="btn btn-primary btn-lg" href="{% url 'users:update' %}" role="button">Update</a>
                    <a class="infobutton btn btn-secondary btn-lg" href="{% url 'users:update_image' %}" role="button">Update photo</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/info_book.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

   <h1 class="text-center logo my-4">
      Book's Info
   </h1>


    <div class="card mb-2" style="margin-left:5%; margin-right:10%;">
        <div class="card-body p-3" >
            <div class="row">

                <div class="col-4" style="margin-top:15%;">
                    <img src="{{ book.image }}" class="center">
                </div>

                <div class="col-6">
                        <p class="lead">Id: {{ book.id }}</p>
                    <hr class="my-4">
                        <p class="lead">Title: {{ book.title }}</p>
                    <hr class="my-4">
                        <p class="lead">Author: {{ book.author }}</p>
                    <hr class="my-4">
                        <p class="lead">Genre: {{ book.genre_1 }}</p>
                    <hr class="my-4">
                        <p class="lead">Reader: {{ book_position.user }}</p>
                    <hr class="my-4">
                        <p class="lead">Month of reading: {{ book_position.month }}</p>
                    <hr class="my-4">
                        <p class="lead">Status: {{ book_position.status }}</p>
                    <hr class="my-4">
                        <a class="btn btn-primary btn-lg" href="{% url 'users:update_book' %}" role="button">Update</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/library.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1 class="text-center logo my-4">
    {{request.user}}'s Library
</h1>

<div class="card-body p-3">
    <div class="tab" >
      <button class="tablinks" onclick="openCategory(event, 'To do')">To do</button>
      <button class="tablinks" onclick="openCategory(event, 'In progress')" id="defaultOpen">In progress</button>
      <button class="tablinks" onclick="openCategory(event, 'Done')">Done</button>
    </div>
</div>


<!--TO DO TAB DIV-->
<div id="To do" class="tabcontent">

{% if books|length == 0 %}
<div class="container">
     <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <form method="POST">
                <p class="lead">Your library is empty :(</p>
                <p class="lead">You can find some books by clicking on "Find books" button in menu or by clicking button
                right there!</p>
                <hr class="my-4">

            <a class="btn btn-primary" href="{% url 'books:find' %}" role="button">Find books</a> <a href='../'>Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% else %}
{% for book_position in users_book_positions %}
    {% for book in books %}
        {% ifequal book.title|stringformat:"s" book_position.book|stringformat:"s" %}
            {% ifequal book_position.status|stringformat:"s" "To do" %}
            <div class="card mb-2" style="margin-left:10%; margin-right:10%;" id="div{{ book.id }}">
                <div class="card-body p-3">
                    <div class="row">

                        <div class="col-2">
                            <img src="{{ book.image }}" class="center">
                        </div>

                         <div class="col-10">
                                <div class="row mb-3">
                                    <div class="col-6">
                                        <p><strong class="text-dark">{{ book.title }}</strong></p>
                                        <small class="text-muted">{{ book.author }}</small>
                                        <br>
                                    </div>
                                    <div class="col-6" style="text-align:right;">
                                        <small class="text-muted">ID: {{ book.id }}</small>
                                    </div>
                                </div>

                            <hr class="my-4">
                            {% if book.description == None %}
                            There is no description :(
                            {% else %}
                            {{ book.description }}
                            {% endif %}
                            <p>
                            <br>

                             <form method="post" action="{% url 'users:info_book' %}">
                                {%csrf_token%}
                                <div type="text/css" class = "container"></div>
                                <a class="addbutton btn btn-danger btn-lg" id="like{{ book.id }}" href="#" data-catid="{{ book.id }}">Delete</a>
                                <input type="hidden"  name="id" value="{{ book.id }}">
                                <button class="infobutton btn btn-secondary btn-lg" type="submit">Update</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        {% endifequal %}
        {% endifequal %}
    {% endfor %}
{% endfor %}
{% endif %}
</div>


<!--IN PROGRESS TAB DIV-->
<div id="In progress" class="tabcontent">

{% if books|length == 0 %}
<div class="container">
     <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <form method="POST">
                <p class="lead">Your library is empty :(</p>
                <p class="lead">You can find some books by clicking on "Find books" button in menu or by clicking button
                right there!</p>
                <hr class="my-4">

            <a class="btn btn-primary" href="{% url 'books:find' %}" role="button">Find books</a> <a href='../'>Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% else %}
{% for book_position in users_book_positions %}
    {% for book in books %}
        {% ifequal book.title|stringformat:"s" book_position.book|stringformat:"s" %}
            {% ifequal book_position.status|stringformat:"s" "In progress" %}
                <div class="card mb-2" style="margin-left:10%; margin-right:10%;" id="div{{ book.id }}">
                    <div class="card-body p-3">
                        <div class="row">

                            <div class="col-2">
                                <img src="{{ book.image }}" class="center">
                            </div>

                             <div class="col-10">
                                    <div class="row mb-3">
                                        <div class="col-6">
                                            <p><strong class="text-dark">{{ book.title }}</strong></p>
                                            <small class="text-muted">{{ book.author }}</small>
                                            <br>
                                        </div>
                                        <div class="col-6" style="text-align:right;">
                                            <small class="text-muted">ID: {{ book.id }}</small>
                                        </div>
                                    </div>

                                <hr class="my-4">
                                {% if book.description == None %}
                                There is no description :(
                                {% else %}
                                {{ book.description }}
                                {% endif %}
                                <p>
                                <br>

                                 <form method="post" action="{% url 'users:info_book' %}">
                                    {%csrf_token%}
                                    <div type="text/css" class = "container"></div>
                                    <a class="addbutton btn btn-danger btn-lg" id="like{{ book.id }}" href="#" data-catid="{{ book.id }}">Delete</a>
                                    <input type="hidden"  name="id" value="{{ book.id }}">
                                    <button class="infobutton btn btn-secondary btn-lg" type="submit">Update</button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

            {% endifequal %}
        {% endifequal %}
    {% endfor %}
{% endfor %}
{% endif %}
</div>


<!--DONE TAB DIV-->
<div id="Done" class="tabcontent">

{% if books|length == 0 %}
<div class="container">
     <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <form method="POST">
                <p class="lead">Your library is empty :(</p>
                <p class="lead">You can find some books by clicking on "Find books" button in menu or by clicking button
                right there!</p>
                <hr class="my-4">

            <a class="btn btn-primary" href="{% url 'books:find' %}" role="button">Find books</a> <a href='../'>Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% else %}
{% for book_position in users_book_positions %}
    {% for book in books %}
        {% ifequal book.title|stringformat:"s" book_position.book|stringformat:"s" %}
            {% ifequal book_position.status|stringformat:"s" "Done" %}
                <div class="card mb-2" style="margin-left:10%; margin-right:10%;" id="div{{ book.id }}">
                    <div class="card-body p-3">
                        <div class="row">

                            <div class="col-2">
                                <img src="{{ book.image }}" class="center">
                            </div>

                             <div class="col-10">
                                    <div class="row mb-3">
                                        <div class="col-6">
                                            <p><strong class="text-dark">{{ book.title }}</strong></p>
                                            <small class="text-muted">{{ book.author }}</small>
                                            <br>
                                        </div>
                                        <div class="col-6" style="text-align:right;">
                                            <small class="text-muted">ID: {{ book.id }}</small>
                                        </div>
                                    </div>

                                <hr class="my-4">
                                {% if book.description == None %}
                                There is no description :(
                                {% else %}
                                {{ book.description }}
                                {% endif %}
                                <p>
                                <br>

                                 <form method="post" action="{% url 'users:info_book' %}">
                                    {%csrf_token%}
                                    <div type="text/css" class = "container"></div>
                                    <a class="addbutton btn btn-danger btn-lg" id="like{{ book.id }}" href="#" data-catid="{{ book.id }}">Delete</a>
                                    <input type="hidden"  name="id" value="{{ book.id }}">
                                    <button class="infobutton btn btn-secondary btn-lg" type="submit">Update</button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

            {% endifequal %}
        {% endifequal %}
    {% endfor %}
{% endfor %}
{% endif %}
</div>

<script src="/static/js/library_script.js"></script>
<script src="/static/js/back_to_top_script.js"></script>

{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

   <h1 class="text-center logo my-4">
      Login
   </h1>

<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input class="btn btn-primary btn-lg" type="Submit" value="Login" /> <a href='../'>Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

   <h1 class="text-center logo my-4">
      Register
   </h1>

<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary btn-lg" type="Submit" value="Register" /> <a href='../'>Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/users/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

   <h1 class="text-center logo my-4">
      Update
   </h1>

<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary btn-lg" type="Submit" value="Update" /> <a href='../'>Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/users/update_book.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

   <h1 class="text-center logo my-4">
      Update book - {{ request.session.book_title }}
   </h1>

<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary btn-lg" type="Submit" value="Update" /> <a href="{% url 'users:library' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/users/update_image.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

   <h1 class="text-center logo my-4">
      Update Image
   </h1>

<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary btn-lg" type="Submit" value="Update" /> <a href='../'>Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}